# Generated by Django 5.2.5 on 2025-09-02 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_department_employee_esi_employee_pf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.notification')),
            ],
            options={
                'unique_together': {('employee', 'notification')},
            },
        ),
    ]
