# Generated by Django 5.2.5 on 2025-09-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_employeenotificationread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeNotificationRead',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
