# Generated by Django 5.2.5 on 2025-09-04 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_delete_employeenotificationread_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorksheetParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('transaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_no', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('worksheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particulars', to='management.worksheet')),
            ],
        ),
    ]
