# Generated by Django 5.2.5 on 2025-09-04 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_worksheet_worksheetparticular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='management.employee')),
            ],
            options={
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
