# Generated by Django 5.2.5 on 2025-09-07 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_employee_password_attendancesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='logout_reason',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BreakSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('logout_reason', models.CharField(max_length=250)),
                ('approved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_sessions', to='management.employee')),
            ],
        ),
    ]
