# Generated by Django 5.2.5 on 2025-09-07 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_attendancesession_logout_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('total_commission', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='management.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('work_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_mobile_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('stage', models.CharField(choices=[('start', 'Start'), ('stage2', 'Stage 2'), ('stage3', 'Stage 3'), ('stage4', 'Stage 4'), ('complete', 'Complete')], default='start', max_length=10)),
                ('expected_time_to_complete', models.DurationField(help_text='Expected time to complete the work')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.BooleanField(default=False)),
                ('assigned_employees', models.ManyToManyField(related_name='work_orders', to='management.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
