# Generated by Django 5.2.5 on 2025-09-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='expected_time_to_complete',
        ),
        migrations.AddField(
            model_name='workorder',
            name='expected_days_to_complete',
            field=models.PositiveIntegerField(default=1, help_text='Expected number of days to complete the work'),
        ),
    ]
