# Generated by Django 5.2.5 on 2025-09-07 13:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheetparticular',
            name='worksheet',
        ),
        migrations.CreateModel(
            name='WorkCompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=255)),
                ('service', models.CharField(max_length=255)),
                ('transaction_no', models.CharField(blank=True, max_length=255, null=True)),
                ('certificate_no', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works_completed', to='management.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Worksheet',
        ),
        migrations.DeleteModel(
            name='WorksheetParticular',
        ),
    ]
