# Generated by Django 5.2.5 on 2025-09-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_remove_worksheetparticular_worksheet_workcompleted_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkCompleted',
        ),
    ]
