# Generated by Django 5.2.5 on 2025-09-09 09:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_delete_workcompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='session_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='breaksession',
            name='ended_by_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breaksession',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='breaksession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
