# Generated by Django 5.2.5 on 2025-09-09 09:58

from django.db import migrations
import uuid

def assign_uuids(apps, schema_editor):
    AttendanceSession = apps.get_model('management', 'AttendanceSession')
    for obj in AttendanceSession.objects.filter(uuid__isnull=True):
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=['uuid'])

    BreakSession = apps.get_model('management', 'BreakSession')
    for obj in BreakSession.objects.filter(uuid__isnull=True):
        obj.uuid = uuid.uuid4()
        obj.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_attendancesession_session_closed_and_more'),
    ]

    operations = [
        migrations.RunPython(assign_uuids, reverse_code=migrations.RunPython.noop),
    ]
