# Generated by Django 5.2.5 on 2025-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_alter_attendancesession_uuid_alter_breaksession_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
