# Generated by Django 5.2.5 on 2025-09-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_attendancesession_last_ping'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Enter full IP address (e.g., 192.168.1.100) or subnet (e.g., 192.168.1.0/24)')),
                ('subnet_prefix', models.CharField(blank=True, help_text="For subnet matching, enter prefix (e.g., '192.168.1.' or '10.0.')", max_length=20, null=True)),
                ('description', models.CharField(blank=True, help_text="Description of this IP/location (e.g., 'Office WiFi', 'John's Home')", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to temporarily disable this IP without deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allowed IP Address',
                'verbose_name_plural': 'Allowed IP Addresses',
                'ordering': ['-created_at'],
            },
        ),
    ]
