# Generated by Django 5.2.5 on 2025-09-11 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_allowedip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('application_name', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_mobile_number', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('expected_days_to_complete', models.PositiveIntegerField(default=1, help_text='Expected number of days to complete the work')),
                ('total_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of the commission for this employee', max_digits=5)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.application')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
            ],
            options={
                'unique_together': {('application', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='application',
            name='assigned_employees',
            field=models.ManyToManyField(related_name='applications', through='management.ApplicationAssignment', to='management.employee'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='management.application')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
