# Generated by Django 5.2.5 on 2025-09-12 07:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_application_applicationassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('department_name', models.CharField(editable=False, max_length=50)),
                ('token_no', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_num', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Number')),
                ('enrollment_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Enrollment Number')),
                ('login_mobile_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='Login Mobile No.')),
                ('application_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Application No.')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('particulars', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worksheet_entries', to='management.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
