# Generated by Django 5.2.5 on 2025-09-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_worksheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
