# Generated by Django 5.2.5 on 2025-09-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_notification_usernotificationstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='customer_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
