# Generated by Django 5.2.5 on 2025-09-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_monthlydeduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='123', max_length=128),
        ),
    ]
