# Generated by Django 5.2.5 on 2025-09-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_employee_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='A brief description of the uploaded file.')),
                ('file', models.FileField(upload_to='employee_uploads/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to='management.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
