# Generated by Django 5.2.5 on 2025-09-19 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_employeeupload'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlydeduction',
            unique_together=set(),
        ),
    ]
