# Generated by Django 5.2.5 on 2025-09-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_alter_monthlydeduction_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalIPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_all_ips', models.BooleanField(default=False, help_text='If checked, the IP restriction middleware will be disabled and all IPs will be allowed.')),
            ],
            options={
                'verbose_name_plural': 'Global IP Settings',
            },
        ),
    ]
