# Generated by Django 5.2.5 on 2025-09-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_uploadservice_employeeupload_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='expected_days_to_complete',
        ),
        migrations.RemoveField(
            model_name='applicationassignment',
            name='commission_percentage',
        ),
        migrations.AddField(
            model_name='application',
            name='expected_date_of_completion',
            field=models.DateField(blank=True, help_text='Expected date to complete the work', null=True),
        ),
        migrations.AddField(
            model_name='applicationassignment',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The exact commission amount for this employee', max_digits=10),
        ),
    ]
