# Generated by Django 5.2.5 on 2025-09-21 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_remove_application_expected_days_to_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDateExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_extensions', to='management.application')),
                ('extended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
