# Generated by Django 5.2.5 on 2025-09-22 06:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_applicationdateextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlydeduction',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Creation date of the deduction record', null=True),
        ),
    ]
