# Generated by Django 5.2.5 on 2025-09-22 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_monthlydeduction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="A short, descriptive name for the link (e.g., 'Company Policy Document').", max_length=200)),
                ('url', models.URLField(help_text="The full URL of the link (e.g., 'https://example.com/policy.pdf').", max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Managed Link',
                'verbose_name_plural': 'Managed Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLinkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_assignments', to='management.employee')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to='management.managedlink')),
            ],
            options={
                'verbose_name': 'Employee Link Assignment',
                'verbose_name_plural': 'Employee Link Assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('employee', 'link')},
            },
        ),
    ]
