# Generated by Django for Worksheet.created_at addition
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_monthlydeduction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterModelOptions(
            name='worksheet',
            options={'ordering': ['-created_at']},
        ),
    ]
