# Generated by Django 5.2.5 on 2025-09-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_managedlink_employeelinkassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managedlink',
            options={'ordering': ['description'], 'verbose_name': 'Managed Link', 'verbose_name_plural': 'Managed Links'},
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_links',
            field=models.ManyToManyField(blank=True, related_name='assigned_employees', to='management.managedlink'),
        ),
    ]
