# Generated by Django 5.2.5 on 2025-09-23 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0036_todotask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todotask',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='todotask',
            name='reminder_shown',
        ),
        migrations.AlterField(
            model_name='todotask',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='management.employee'),
        ),
    ]
