# Generated by Django 5.2.5 on 2025-09-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0037_remove_todotask_completed_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoTask',
        ),
    ]
