# Generated by Django 5.2.5 on 2025-09-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0039_todotask'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='advances',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total outstanding advance amount taken by the employee.', max_digits=10, verbose_name='Current Advance'),
        ),
        migrations.CreateModel(
            name='MonthlyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('meetings_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('trainings_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bonuses', to='management.employee')),
            ],
            options={
                'verbose_name': 'Monthly Bonus',
                'verbose_name_plural': 'Monthly Bonuses',
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
