# Generated by Django 5.2.5 on 2025-09-25 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_employee_advances_monthlybonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(help_text='e.g., Weekly Sync, Project Kick-off', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid to each employee who attends.', max_digits=10, verbose_name='Bonus Amount')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.employee')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.meeting')),
            ],
            options={
                'unique_together': {('meeting', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings_attended', through='management.MeetingAttendance', to='management.employee'),
        ),
    ]
