# Generated by Django 5.2.5 on 2025-09-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_meeting_meetingattendance_meeting_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="A custom name for the link (e.g., 'main-logo', 'promo-banner').", max_length=100, null=True)),
                ('image', models.ImageField(upload_to='shared_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
