# Generated by Django 5.2.5 on 2025-09-25 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_sharedimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedImage',
        ),
    ]
