# Generated by Django 5.2.5 on 2025-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_delete_sharedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='bonds_sno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bonds Sl. No'),
        ),
    ]
