# Generated by Django 5.2.5 on 2025-09-28 19:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_worksheet_bonds_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRepairReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('monitor_status', models.CharField(choices=[('OK', 'OK'), ('Repair', 'Needs Repair')], default='OK', max_length=10)),
                ('cpu_status', models.CharField(choices=[('OK', 'OK'), ('Repair', 'Needs Repair')], default='OK', max_length=10)),
                ('keyboard_status', models.CharField(choices=[('OK', 'OK'), ('Repair', 'Needs Repair')], default='OK', max_length=10)),
                ('mouse_status', models.CharField(choices=[('OK', 'OK'), ('Repair', 'Needs Repair')], default='OK', max_length=10)),
                ('cables_status', models.CharField(choices=[('OK', 'OK'), ('Repair', 'Needs Repair')], default='OK', max_length=10)),
                ('printer_status', models.CharField(choices=[('OK', 'OK'), ('Repair', 'Needs Repair')], default='OK', max_length=10)),
                ('bike_status', models.CharField(choices=[('OK', 'OK'), ('Repair', 'Needs Repair')], default='OK', max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repair_reports', to='management.employee')),
            ],
            options={
                'ordering': ['-date', 'employee'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_daily_report_per_employee')],
            },
        ),
    ]
