# Generated by Django 5.2.5 on 2025-10-01 07:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_employee_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(help_text='e.g., Exceeded Sales Target, Project Completion Bonus', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonus Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_bonuses', to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(help_text='e.g., Advanced Python Course, Safety Protocol Training', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonus Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_bonuses', to='management.employee')),
            ],
        ),
    ]
