# Generated by Django 5.2.5 on 2025-10-01 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_performancebonus_trainingbonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyBonus',
        ),
    ]
