# Generated by Django 5.2.5 on 2025-10-05 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_delete_monthlybonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('referee_commission_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage of the total commission for the employee creating the application when it is shared.', max_digits=5, verbose_name='Referee Commission (%)')),
                ('partner_commission_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage of the total commission for the employee the application is shared with.', max_digits=5, verbose_name='Partner Commission (%)')),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='application_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.AddField(
            model_name='application',
            name='service_type',
            field=models.ForeignKey(blank=True, help_text='Select the type of service for this application.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='management.servicetype'),
        ),
    ]
