# Generated by Django 5.2.5 on 2025-11-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0049_servicetype_remove_application_application_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeupload',
            name='renewal_date',
            field=models.DateField(blank=True, help_text='Date when this upload needs to be renewed (automatically set to 1 year from upload date)', null=True),
        ),
    ]
