# Generated by Django 5.2.5 on 2025-11-05 15:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_employeeupload_renewal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraDaysBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(help_text='e.g., Weekend Work, Extra Hours, Holiday Work', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Bonus Amount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_days_bonuses', to='management.employee')),
            ],
        ),
    ]
