# Generated by Django 5.2.5 on 2025-11-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0051_extradaysbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeupload',
            name='mobile_number',
            field=models.CharField(blank=True, help_text='Mobile number related to this upload', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeeupload',
            name='renewal_date',
            field=models.DateField(blank=True, help_text='Date when this upload needs to be renewed', null=True),
        ),
    ]
