# Generated by Django 5.2.5 on 2025-11-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_employeeupload_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='refreshed_at',
            field=models.DateTimeField(blank=True, help_text='Last time this session was refreshed.', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_expires_at',
            field=models.DateTimeField(blank=True, help_text='When this 15-min session will expire.', null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='session_status',
            field=models.CharField(default='active', help_text='active, refreshed, expired, or ended.', max_length=32),
        ),
    ]
