# Generated by Django 5.2.5 on 2025-11-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_attendancesession_refreshed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('latitude', models.FloatField(help_text='Latitude of the center point')),
                ('longitude', models.FloatField(help_text='Longitude of the center point')),
                ('radius_meters', models.PositiveIntegerField(default=100, help_text='Radius in meters')),
                ('active', models.BooleanField(default=True, help_text='Is this area currently enforced?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeofenceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Enable geofencing for employee access')),
            ],
            options={
                'verbose_name': 'Geofencing Settings',
                'verbose_name_plural': 'Geofencing Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='todotask',
            options={'verbose_name': 'Assign task', 'verbose_name_plural': 'Assign tasks'},
        ),
    ]
