# Generated by Django 5.2.5 on 2025-11-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_attendancesession_refreshed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todotask',
            options={'verbose_name': 'Assign task', 'verbose_name_plural': 'Assign tasks'},
        ),
    ]
