# Generated by Django 5.2.5 on 2025-11-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_accessarea_geofencesettings_alter_todotask_options'),
        ('management', '0054_alter_todotask_options'),
    ]

    operations = [
    ]
