# Generated by Django 5.2.5 on 2025-11-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_merge_20251108_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='completed',
            field=models.BooleanField(default=False, help_text='Task completed status'),
        ),
    ]
