# Generated by Django 5.2.5 on 2025-11-10 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0017_add_actor_email'),
        ('management', '0057_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry',),
        ),
    ]
