# Generated by Django 5.2.5 on 2025-12-13 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0034_worksheet_created_at'),
        ('management', '0058_logentry_userprofile'),
    ]

    operations = [
    ]
