# Generated by Django 5.2.5 on 2025-11-10 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_logentry'),
        ('management', '0058_logentry_userprofile'),
    ]

    operations = [
    ]
