# Generated by Django 5.2.5 on 2025-12-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_merge_0058_logentry_0058_logentry_userprofile'),
        ('management', '0059_merge_20251213_1413'),
    ]

    operations = [
    ]
