# Generated by Django 5.2.5 on 2025-12-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_merge_20251213_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default amount for this service type.', max_digits=10, verbose_name='Amount'),
        ),
    ]
