# Generated by Django 5.2.5 on 2025-12-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_servicetype_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='locked',
            field=models.BooleanField(default=False, help_text='If checked, this employee is locked and cannot access the system.'),
        ),
    ]
