# Generated by Django 5.2.5 on 2026-02-15 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0062_employee_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department to which this service type belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_types', to='management.department'),
        ),
    ]
