# Generated by Django 5.2.5 on 2026-02-15 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0063_servicetype_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetype',
            name='partner_commission_percentage',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='referee_commission_percentage',
        ),
    ]
