# Generated by Django 5.2.5 on 2026-02-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0064_remove_servicetype_partner_commission_percentage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.RemoveField(
            model_name='servicetype',
            name='department',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Departments to which this service type belongs.', related_name='service_types', to='management.department'),
        ),
    ]
