# Generated by Django 5.2.5 on 2026-02-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0064_remove_servicetype_partner_commission_percentage_and_more'),
    ]

    operations = [
    ]
