# Generated by Django 5.2.5 on 2026-03-25 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0065_delete_logentry_remove_servicetype_department_and_more'),
        ('management', '0066_remove_servicetype_department_and_more'),
    ]

    operations = [
    ]
