# Generated by Django 5.2.5 on 2026-03-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0067_merge_20260325_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='worksheet_entry_force_unlock',
            field=models.BooleanField(default=False, help_text='If enabled, this employee can add worksheet entries even after the daily 4:00 PM lock.'),
        ),
    ]
