# Generated by Django 5.2.5 on 2026-03-25 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0068_employee_worksheet_entry_force_unlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.ForeignKey(blank=True, help_text='Select the existing employee who is the head/manager of this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='management.employee'),
        ),
    ]
