# Generated by Django 5.2.5 on 2026-03-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0069_department_department_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='management.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
