# Generated by Django 5.2.5 on 2026-03-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0070_departmenttopup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_type', models.CharField(choices=[('100', '100 RPS BONDS'), ('50', '50 RPS BONDS'), ('20', '20 RPS BONDS')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='management.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
