# Generated by Django 5.2.5 on 2026-03-25 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0071_departmentinventoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeNextDayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(help_text='The date for which the employee confirmed availability.')),
                ('will_come', models.BooleanField(default=False)),
                ('response_source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto')], default='manual', max_length=10)),
                ('responded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_day_availability_records', to='management.employee')),
            ],
            options={
                'verbose_name': 'Employee Next Day Availability',
                'verbose_name_plural': 'Employee Next Day Availability',
                'ordering': ['-target_date', '-responded_at'],
                'unique_together': {('employee', 'target_date')},
            },
        ),
    ]
