# Generated by Django 5.2.5 on 2026-03-27 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0074_salarypayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='management.department')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='management.servicetype')),
            ],
            options={
                'ordering': ['service_type__name'],
                'unique_together': {('department', 'service_type')},
            },
        ),
    ]
