# Generated by Django 5.2.5 on 2026-03-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0076_employee_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetarget',
            name='carry_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Unmet balance carried forward from the previous day. Auto-calculated.', max_digits=10),
        ),
    ]
