# Generated by Django 5.2.5 on 2026-03-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0077_employeetarget_carry_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksheet',
            name='amount_image',
            field=models.ImageField(blank=True, null=True, upload_to='worksheet_data/'),
        ),
        migrations.AddField(
            model_name='worksheet',
            name='token_image',
            field=models.ImageField(blank=True, null=True, upload_to='worksheet_data/'),
        ),
    ]
