# Generated by Django 5.2.5 on 2026-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0078_worksheet_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheet',
            name='amount_image',
        ),
        migrations.AddField(
            model_name='worksheet',
            name='particulars_image',
            field=models.ImageField(blank=True, null=True, upload_to='worksheet_data/'),
        ),
    ]
