# Generated by Django 5.2.5 on 2026-03-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0081_add_commission_payment_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='payment_type',
            field=models.CharField(choices=[('salary', 'Salary'), ('commission', 'Commission')], default='salary', max_length=20),
        ),
        migrations.DeleteModel(
            name='CommissionPayment',
        ),
    ]
