# Generated by Django 5.2.5 on 2026-03-28 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0082_add_payment_type_to_salary_remove_commission_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTDGroupSeva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(help_text='Planned date for the group seva')),
                ('num_members', models.PositiveIntegerField(help_text='Number of members in the group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttd_group_sevas', to='management.employee')),
            ],
            options={
                'verbose_name': 'TTD Group Seva',
                'verbose_name_plural': 'TTD Group Sevas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TTDGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(help_text='12-digit Aadhaar number', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='management.ttdgroupseva')),
            ],
            options={
                'verbose_name': 'TTD Group Member',
                'verbose_name_plural': 'TTD Group Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TTDIndividualDarshan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15)),
                ('aadhar_number', models.CharField(help_text='12-digit Aadhaar number', max_length=12)),
                ('planned_date', models.DateField(help_text='Planned date for darshan')),
                ('slot_time', models.CharField(choices=[('06:00', '06:00 AM'), ('07:00', '07:00 AM'), ('08:00', '08:00 AM'), ('09:00', '09:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '01:00 PM'), ('14:00', '02:00 PM'), ('15:00', '03:00 PM'), ('16:00', '04:00 PM'), ('17:00', '05:00 PM'), ('18:00', '06:00 PM')], help_text='Preferred slot time', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ttd_individual_darshans', to='management.employee')),
            ],
            options={
                'verbose_name': 'TTD Individual Darshan',
                'verbose_name_plural': 'TTD Individual Darshans',
                'ordering': ['-created_at'],
            },
        ),
    ]
