# Generated by Django 5.2.5 on 2026-04-01 12:09

import django.db.models.deletion
import management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0085_worksheet_stocks_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_no', models.CharField(default=management.models.generate_token_no, help_text='6-digit random token number', max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Auto-generated date and time')),
                ('customer_name', models.CharField(help_text='Name of the customer', max_length=255)),
                ('cell_no', models.CharField(help_text='Contact number', max_length=15)),
                ('department', models.ForeignKey(help_text='Select department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.department')),
                ('operator_name', models.ForeignKey(help_text='Select active operator/employee', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.employee')),
                ('service_type', models.ForeignKey(help_text='Select service type for the selected department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.servicetype')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
