# Generated by Django 5.2.5 on 2026-04-02 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0095_chatbotnumerictrigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('bot', 'Bot'), ('admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='management.token')),
            ],
            options={
                'verbose_name': 'Token Chat Message',
                'verbose_name_plural': 'Token Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
