# Generated by Django 5.2.5 on 2025-08-31 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_description', models.TextField()),
                ('customer_mobile_number', models.CharField(max_length=15)),
                ('stage', models.CharField(choices=[('start', 'Start'), ('stage2', 'Stage 2'), ('stage3', 'Stage 3'), ('stage4', 'Stage 4'), ('complete', 'Complete')], default='start', max_length=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='management.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='management.employee')),
            ],
            options={
                'verbose_name_plural': 'Attendance records',
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
